import type { ContentFormat } from "./types";

export const FORMATS: ContentFormat[] = [
  {
    id: "post-portrait",
    name: "Post Portrait",
    network: "instagram",
    width: 1080,
    height: 1350,
    sizeLabel: "1080 x 1350px",
    description: "Post vertical para o feed do Instagram.",
    top: true,
  },
  {
    id: "carrossel-portrait",
    name: "Carrossel Portrait",
    network: "instagram",
    width: 1080,
    height: 1350,
    sizeLabel: "1080 x 1350px",
    description: "Vários slides verticais em sequência.",
    top: true,
  },
  {
    id: "stories-unico",
    name: "Stories Único",
    network: "instagram",
    width: 1080,
    height: 1920,
    sizeLabel: "1080 x 1920px",
    description: "Story em tela cheia.",
    top: true,
  },
  {
    id: "stories-carrossel",
    name: "Stories Carrossel",
    network: "instagram",
    width: 1080,
    height: 1920,
    sizeLabel: "1080 x 1920px",
    description: "Sequência de stories em tela cheia.",
  },
  {
    id: "post-quadrado",
    name: "Post Quadrado",
    network: "facebook",
    width: 1080,
    height: 1080,
    sizeLabel: "1080 x 1080px",
    description: "Post quadrado clássico para feed.",
  },
  {
    id: "linkedin-post",
    name: "Post LinkedIn",
    network: "linkedin",
    width: 1200,
    height: 1500,
    sizeLabel: "1200 x 1500px",
    description: "Post profissional para o LinkedIn.",
  },
  {
    id: "tiktok-video",
    name: "TikTok",
    network: "tiktok",
    width: 1080,
    height: 1920,
    sizeLabel: "1080 x 1920px",
    description: "Capa/arte vertical para vídeo do TikTok.",
    top: true,
  },
  {
    id: "whatsapp-status",
    name: "Status WhatsApp",
    network: "whatsapp",
    width: 1080,
    height: 1920,
    sizeLabel: "1080 x 1920px",
    description: "Arte em tela cheia para o Status do WhatsApp.",
    top: true,
  },
  {
    id: "youtube-shorts",
    name: "YouTube Shorts",
    network: "youtube",
    width: 1080,
    height: 1920,
    sizeLabel: "1080 x 1920px",
    description: "Capa vertical para Shorts do YouTube.",
  },
  {
    id: "kwai-video",
    name: "Kwai",
    network: "kwai",
    width: 1080,
    height: 1920,
    sizeLabel: "1080 x 1920px",
    description: "Capa/arte vertical para vídeo do Kwai.",
  },
  {
    id: "pinterest-pin",
    name: "Pin Pinterest",
    network: "pinterest",
    width: 1000,
    height: 1500,
    sizeLabel: "1000 x 1500px",
    description: "Pin vertical (2:3) para o Pinterest.",
  },
  {
    id: "x-post",
    name: "Post X (Twitter)",
    network: "x",
    width: 1600,
    height: 900,
    sizeLabel: "1600 x 900px",
    description: "Imagem horizontal (16:9) para o X.",
  },
];

export function getFormat(id: string): ContentFormat | undefined {
  return FORMATS.find((f) => f.id === id);
}
